INSERT INTO hallocasaapp.property_field(id, name) VALUES (1, "Information - Languages");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (2, "Information - Title");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (3, "Information - Property Description");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (4, "Information - Location Description");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (5, "Information - Market Price");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (6, "Information - Square Meters Total");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (7, "Location - Department");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (8, "Location - Town");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (9, "Location - Address");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (10, "Location - Longitude");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (11, "Location - Latitude");
INSERT INTO hallocasaapp.property_field(id, name) VALUES (12, "Images - Image");