CREATE TABLE `hallocasaapp`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(80) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `first_name` VARCHAR(45)  COMMENT '',
  `last_name` VARCHAR(45)  COMMENT '',
  `state` VARCHAR(45)  COMMENT '',
  `city` VARCHAR(45)  COMMENT '',
  `web_site` VARCHAR(80)  COMMENT '',
  `linked_in` VARCHAR(80)  COMMENT '',
  `skype` VARCHAR(45)  COMMENT '',
  `language` VARCHAR(10) NOT NULL COMMENT '',
  `confirmed_flag` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `user_description` TEXT COMMENT 'JSON (MultilanguageText) with description for each language',
  `spoken_languages` TEXT COMMENT 'JSON with an array of spoken languages',
  `country_id` INT COMMENT '',
  `state_id` INT COMMENT '',
  PRIMARY KEY `pk__user` (`id`)  COMMENT '',
  UNIQUE INDEX `uq__user__email` (`email` ASC)  COMMENT '',
  FOREIGN KEY `fk__user__country` (`country_id`) REFERENCES `hallocasaapp`.`country`(`id`),
  FOREIGN KEY `fk__user__state` (`state_id`) REFERENCES `hallocasaapp`.`state`(`id`) );
