INSERT INTO hallocasaapp.state (ID, STATE_NAME, COUNTRY_ID) VALUES
(1,"{'de':'Amazonas','en':'Amazonas','es':'Amazonas'}",1),
(2,"{'de':'Antioquia','en':'Antioquia','es':'Antioquia'}",1),
(3,"{'de':'Arauca','en':'Arauca','es':'Arauca'}",1),
(4,"{'de':'Atl\\u00E1ntico','en':'Atl\\u00E1ntico','es':'Atl\\u00E1ntico'}",1),
(5,"{'de':'Bol\\u00EDvar','en':'Bol\\u00EDvar','es':'Bol\\u00EDvar'}",1),
(6,"{'de':'Boyac\\u00E1','en':'Boyac\\u00E1','es':'Boyac\\u00E1'}",1),
(7,"{'de':'Caldas','en':'Caldas','es':'Caldas'}",1),
(8,"{'de':'Caquet\\u00E1','en':'Caquet\\u00E1','es':'Caquet\\u00E1'}",1),
(9,"{'de':'Casanare','en':'Casanare','es':'Casanare'}",1),
(10,"{'de':'Cauca','en':'Cauca','es':'Cauca'}",1),
(11,"{'de':'Cesar','en':'Cesar','es':'Cesar'}",1),
(12,"{'de':'Choc\\u00F3','en':'Choc\\u00F3','es':'Choc\\u00F3'}",1),
(13,"{'de':'C\\u00F3rdoba','en':'C\\u00F3rdoba','es':'C\\u00F3rdoba'}",1),
(14,"{'de':'Cundinamarca','en':'Cundinamarca','es':'Cundinamarca'}",1),
(15,"{'de':'G\\u00FCainia','en':'G\\u00FCainia','es':'G\\u00FCainia'}",1),
(16,"{'de':'Guaviare','en':'Guaviare','es':'Guaviare'}",1),
(17,"{'de':'Huila','en':'Huila','es':'Huila'}",1),
(18,"{'de':'La Guajira','en':'La Guajira','es':'La Guajira'}",1),
(19,"{'de':'Magdalena','en':'Magdalena','es':'Magdalena'}",1),
(20,"{'de':'Meta','en':'Meta','es':'Meta'}",1),
(21,"{'de':'Nari\\u00F1o','en':'Nari\\u00F1o','es':'Nari\\u00F1o'}",1),
(22,"{'de':'Norte de Santander','en':'Norte de Santander','es':'Norte de Santander'}",1),
(23,"{'de':'Putumayo','en':'Putumayo','es':'Putumayo'}",1),
(24,"{'de':'Quind\\u00EDo','en':'Quind\\u00EDo','es':'Quind\\u00EDo'}",1),
(25,"{'de':'Risaralda','en':'Risaralda','es':'Risaralda'}",1),
(26,"{'de':'San Andr\\u00E9s y Providencia','en':'San Andr\\u00E9s y Providencia','es':'San Andr\\u00E9s y Providencia'}",1),
(27,"{'de':'Santander','en':'Santander','es':'Santander'}",1),
(28,"{'de':'Sucre','en':'Sucre','es':'Sucre'}",1),
(29,"{'de':'Tolima','en':'Tolima','es':'Tolima'}",1),
(30,"{'de':'Valle del Cauca','en':'Valle del Cauca','es':'Valle del Cauca'}",1),
(31,"{'de':'Vaup\\u00E9s','en':'Vaup\\u00E9s','es':'Vaup\\u00E9s'}",1),
(32,"{'de':'Vichada','en':'Vichada','es':'Vichada'}",1);