USE hallocasaappmig;
SET FOREIGN_KEY_CHECKS=0;
delete from hallocasaappmig.property_type;
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(1,'Lot',1);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(2,'Warehouse - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(3,'Garage - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(4,'Office - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(5,'Kindergarten - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(6,'Restaurante - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(7,'Factory - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(8,'School - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(9,'Theater - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(10,'Hotel - Stand-Alone',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(11,'Shopping Mall',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(12,'Lot with Built',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(13,'Airport',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(14,'Hospital',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(15,'Detached House',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(16,'Apartment Building',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(17,'Airport',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(18,'Finca',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(19,'Car Park',2);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(20,'Warehouse - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(21,'Garage - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(22,'Office - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(23,'Kindergarten - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(24,'Restaurante - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(25,'Factory - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(26,'School - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(27,'Hotel - In-House',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(28,'Apartments',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(29,'Room',3);
INSERT INTO hallocasaappmig.property_type(id, name, group_id) values(30,'Penthouse',3);
SET FOREIGN_KEY_CHECKS=1;