INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (1, 'Canada');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (1, 'North America');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (1, 'United States');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (7, 'Kazakhstan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (7, 'Russia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (20, 'Egypt');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (27, 'South Africa');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (30, 'Greece');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (31, 'Netherlands');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (32, 'Belgium');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (33, 'France');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (34, 'Spain');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (36, 'Hungary');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (39, 'Italy');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (40, 'Romania');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (41, 'Switzerland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (43, 'Austria');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (44, 'United Kingdom');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (45, 'Denmark');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (46, 'Sweden');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (47, 'Norway');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (48, 'Poland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (49, 'Germany');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (51, 'Peru');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (52, 'Mexico');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (53, 'Cuba');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (54, 'Argentina');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (55, 'Brazil');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (56, 'Chile');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (57, 'Colombia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (58, 'Venezuela');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (60, 'Malaysia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (61, 'Australia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (62, 'Indonesia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (63, 'Philippines');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (64, 'New Zealand');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (65, 'Singapore');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (66, 'Thailand');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (81, 'Japan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (82, 'Korea (South)');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (84, 'Viet Nam');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (86, 'China');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (90, 'Turkey');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (91, 'India');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (92, 'Pakistan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (93, 'Afghanistan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (94, 'Sri Lanka');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (95, 'Myanmar (Burma)');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (98, 'Iran');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (212, 'Morocco');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (213, 'Algeria');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (216, 'Tunisia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (218, 'Libya');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (220, 'Gambia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (221, 'Senegal');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (222, 'Mauritania');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (223, 'Mali');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (224, 'Guinea');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (225, 'Ivory Coast');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (226, 'Burkina Faso');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (227, 'Niger');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (228, 'Togo');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (229, 'Benin');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (230, 'Mauritius');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (231, 'Liberia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (232, 'Sierra Leone');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (233, 'Ghana');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (234, 'Nigeria');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (235, 'Chad');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (236, 'Central African Rep.');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (237, 'Cameroon');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (238, 'Cape Verde');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (239, 'São Tomé & Príncipe');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (240, 'Equatorial Guinea');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (241, 'Gabon');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (242, 'Congo');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (243, 'Dem. Rep. Congo');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (244, 'Angola');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (245, 'Guinea-Bissau');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (246, 'Diego Garcia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (247, 'Ascension');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (248, 'Seychelles');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (249, 'Sudan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (250, 'Rwanda');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (251, 'Ethiopia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (252, 'Somalia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (253, 'Djibouti');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (254, 'Kenya');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (255, 'Tanzania');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (256, 'Uganda');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (257, 'Burundi');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (258, 'Mozambique');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (260, 'Zambia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (261, 'Madagascar');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (262, 'French Indian Ocean');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (263, 'Zimbabwe');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (264, 'Namibia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (265, 'Malawi');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (266, 'Lesotho');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (267, 'Botswana');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (268, 'Swaziland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (269, 'Comoros');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (290, 'Saint Helena');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (291, 'Eritrea');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (297, 'Aruba');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (298, 'Faroe Islands');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (299, 'Greenland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (350, 'Gibraltar');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (351, 'Portugal');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (352, 'Luxembourg');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (353, 'Ireland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (354, 'Iceland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (355, 'Albania');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (356, 'Malta');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (357, 'Cyprus');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (358, 'Finland');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (359, 'Bulgaria');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (370, 'Lithuania');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (371, 'Latvia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (372, 'Estonia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (373, 'Moldova');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (374, 'Armenia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (375, 'Belarus');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (376, 'Andorra');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (377, 'Monaco');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (378, 'San Marino');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (380, 'Ukraine');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (381, 'Serbia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (382, 'Montenegro');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (385, 'Croatia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (386, 'Slovenia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (387, 'Bosnia - Herzegovina');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (388, 'European Numbers');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (389, 'Macedonia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (420, 'Czech Republic');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (421, 'Slovakia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (423, 'Liechtenstein');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (500, 'Falkland Islands');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (501, 'Belize');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (502, 'Guatemala');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (503, 'El Salvador');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (504, 'Honduras');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (505, 'Nicaragua');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (506, 'Costa Rica');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (507, 'Panama');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (508, 'St Pierre & Miquélon');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (509, 'Haiti');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (590, 'Guadeloupe');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (591, 'Bolivia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (592, 'Guyana');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (593, 'Ecuador');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (594, 'Guiana (French)');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (595, 'Paraguay');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (596, 'Martinique');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (597, 'Suriname');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (598, 'Uruguay');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (599, 'Netherlands Antilles');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (670, 'Timor-Leste');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (673, 'Brunei Darussalam');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (674, 'Nauru');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (675, 'Papua New Guinea');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (676, 'Tonga');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (677, 'Solomon Islands');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (678, 'Vanuatu');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (679, 'Fiji');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (680, 'Palau');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (681, 'Wallis and Futuna');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (682, 'Cook Islands');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (683, 'Niue');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (685, 'Western Samoa');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (686, 'Kiribati');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (687, 'New Caledonia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (688, 'Tuvalu');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (689, 'French Polynesia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (690, 'Tokelau');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (691, 'Micronesia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (692, 'Marshall Islands');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (850, 'Korea (North)');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (852, 'Hong Kong');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (853, 'Macau');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (855, 'Cambodia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (856, 'Laos');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (880, 'Bangladesh');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (886, 'Taiwan/"reserved"');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (960, 'Maldives');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (961, 'Lebanon');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (962, 'Jordan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (963, 'Syria');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (964, 'Iraq');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (965, 'Kuwait');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (966, 'Saudi Arabia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (967, 'Yemen');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (968, 'Oman');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (970, 'Palestine');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (971, 'United Arab Emirates');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (972, 'Israel');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (973, 'Bahrain');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (974, 'Qatar');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (975, 'Bhutan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (976, 'Mongolia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (977, 'Nepal');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (992, 'Tajikistan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (993, 'Turkmenistan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (994, 'Azerbaijan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (995, 'Georgia');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (996, 'Kyrgyzstan');
INSERT INTO `hallocasaapp`.`telephone_prefix` (prefix, description) VALUES  (998, 'Uzbekistan
