package com.hallocasa.business.services.base;

import javax.transaction.NotSupportedException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import javax.transaction.UserTransaction;

import org.eclipse.persistence.exceptions.DatabaseException;

/**
 * This is the superclass of all services
 * 
 * @author davidmantilla
 *
 */
public abstract class ServicesBase {

	/**
	 * Search the databaseException inside
	 * 
	 * @param re
	 *            Rollback exception generated by the user transaction
	 * @return null if the databaseException is not found
	 */
	protected DatabaseException unwrapDatabaseException(RollbackException re) {
		Throwable ex = re;
		while (ex != null) {
			if (ex instanceof DatabaseException) {
				return (DatabaseException) ex;
			}
			ex = ex.getCause();
		}
		return null;
	}

	/**
	 * Rollback user transaction
	 * 
	 * @param txn
	 */
	protected void rollbackTransaction(UserTransaction txn) {
		try {
			txn.rollback();
		} catch (IllegalStateException | SecurityException | SystemException e1) {
			throw new RuntimeException(e1);
		}
	}

	/**
	 * Begin transaction
	 * 
	 * @param txn
	 */
	protected void beginTransaction(UserTransaction txn) {
		try {
			txn.begin();
		} catch (SystemException | NotSupportedException e1) {
			throw new RuntimeException(e1);
		}
	}

}
