USE hallocasaappmig;
START TRANSACTION;
DELETE FROM property_field_value;
DELETE FROM property WHERE property_id = 'tEsTpRoP';
UPDATE property_field SET text_type='INT' WHERE id = 35;
INSERT INTO property (property_id, property_type_id, property_proposal_id, property_location_id, user_id, country_id, publish_date) VALUES ('tEsTPRoP', 1, 1, 1, 1, 1, '2016-11-15 10:25:33');
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 1, 1, null, null, null, null, 1);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 1, 2, null, null, null, null, 17);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 2, null, null, '1', 'titulo', null, 18);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 2, null, null, '2', 'title', null, 19);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 3, null, null, '1', 'descripcion', null, 20);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 3, null, null, '2', 'description', null, 21);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 4, null, null, '1', 'ubicacion', null, 22);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 4, null, null, '2', 'location', null, 23);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 5, null, null, '1', '150000', null, 24);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 6, null, '50', null, null, null, 25);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 7, 2, null, null, null, null, 26);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 8, 3, null, null, null, null, 27);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 9, null, 'my address', null, null, null, 28);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 10, null, null, '2.5', '72.5', null, 29);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 12, null, null, 'tEsTpRoP-randomra.jpg', '0', null, 30);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 12, null, null, 'tEsTpRoP-randomrb.jpg', '0', null, 31);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 12, null, null, 'tEsTpRoP-randomrc.jpg', '1', null, 32);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 13, null, 'http://www.youtube.com/thevideo', null, null, null, 33);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 15, 2, null, null, null, null, 34);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 17, null, '2', null, null, null, 35);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 18, null, '2', null, null, null, 36);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 19, 1, null, null, null, null, 37);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 19, 2, null, null, null, null, 38);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 19, 3, null, null, null, null, 39);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 36, 1, null, null, null, null, 40);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 36, 2, null, null, null, null, 41);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 36, 3, null, null, null, null, 42);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 20, null, '1', null, null, null, 43);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 21, null, '1', null, null, null, 44);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 24, null, '2', null, null, null, 45);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 25, null, '0', null, null, null, 46);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 27, null, '0', null, null, null, 47);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 28, null, '1', null, null, null, 48);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 29, null, '2017-01-01', null, null, null, 49);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 30, null, '0', null, null, null, 50);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 35, null, '13', null, null, null, 51);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 22, 1, null, null, null, null, 52);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 23, 2, null, null, null, null, 53);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 23, 3, null, null, null, null, 54);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 23, 1, null, null, null, null, 55);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 22, 2, null, null, null, null, 56);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 22, 3, null, null, null, null, 57);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 37, 4, null, null, null, null, 59);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 44, 1, null, null, null, null, 60);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 46, null, '13', null, null, null, 66);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 57, null, '4.5', null, null, null, 84);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 58, null, '3.5', null, null, null, 85);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 60, null, '1200000', null, null, null, 86);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 44, 2, null, null, null, null, 87);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 44, 3, null, null, null, null, 88);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 47, 2, null, null, null, null, 89);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 47, 3, null, null, null, null, 90);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 48, 2, null, null, null, null, 91);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 48, 3, null, null, null, null, 92);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 49, 7, null, null, null, null, 93);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 50, 4, null, null, null, null, 94);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 51, 1, null, null, null, null, 95);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 51, 2, null, null, null, null, 96);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 51, 3, null, null, null, null, 97);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 52, 1, null, null, null, null, 98);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 52, 2, null, null, null, null, 99);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 52, 3, null, null, null, null, 100);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 53, 1, null, null, null, null, 101);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 54, 4, null, null, null, null, 102);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 55, 3, null, null, null, null, 103);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 55, 4, null, null, null, null, 104);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 55, 5, null, null, null, null, 105);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 56, 2, null, null, null, null, 106);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 59, 2, null, null, null, null, 107);
INSERT INTO property_field_value (property_id, property_field_id, identifier, text, data1, data2, data3, id) VALUES ('tEsTpRoP', 45, 1, null, null, null, null, 108);
COMMIT;